In [1]:
import pandas as pd
from pathlib import Path

In [2]:
root_dir = Path.cwd()
if not (root_dir / "data").exists():
    root_dir = root_dir.parent
if not (root_dir / "data").exists():
    raise FileNotFoundError("Could not locate project root containing the data directory.")

bronze_dir = root_dir / "data" / "bronze"
bronze_dir.mkdir(parents=True, exist_ok=True)

gdp_path = bronze_dir / "bronze_gdp.csv"
pop_path = bronze_dir / "bronze_pop.csv"
matches_path = bronze_dir / "bronze_wc_matches.csv"

In [3]:
gdp = pd.read_csv(gdp_path)
pop = pd.read_csv(pop_path)
matches = pd.read_csv(matches_path)

In [4]:
gdp.head()

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2020,2021,2022,2023,2024,2025,Unnamed: 70,source_name,load_timestamp,run_id
0,Aruba,ABW,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,2.471419e+09,2.880903e+09,3.324034e+09,3.834730e+09,4.265651e+09,NaN,NaN,fifa_world_cup_archive,2026-06-30 08:46:51,58017eb6-8dc6-4e9f-972a-595dedc8aa74
1,Africa Eastern and Southern,AFE,GDP (current US$),NY.GDP.MKTP.CD,2.420569e+10,2.495889e+10,2.707323e+10,3.176914e+10,3.027955e+10,3.380618e+10,...,9.386076e+11,1.114145e+12,1.228968e+12,1.179359e+12,1.242694e+12,NaN,NaN,fifa_world_cup_archive,2026-06-30 08:46:51,58017eb6-8dc6-4e9f-972a-595dedc8aa74
2,Afghanistan,AFG,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,1.995593e+10,1.426000e+10,1.449724e+10,1.715223e+10,NaN,NaN,NaN,fifa_world_cup_archive,2026-06-30 08:46:51,58017eb6-8dc6-4e9f-972a-595dedc8aa74
3,Africa Western and Central,AFW,GDP (current US$),NY.GDP.MKTP.CD,1.190481e+10,1.270772e+10,1.363059e+10,1.446891e+10,1.580356e+10,1.692088e+10,...,9.637847e+11,1.026651e+12,1.063649e+12,9.382384e+11,7.363850e+11,NaN,NaN,fifa_world_cup_archive,2026-06-30 08:46:51,58017eb6-8dc6-4e9f-972a-595dedc8aa74
4,Angola,AGO,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,5.885246e+10,7.955954e+10,1.312122e+11,1.071677e+11,1.009989e+11,NaN,NaN,fifa_world_cup_archive,2026-06-30 08:46:51,58017eb6-8dc6-4e9f-972a-595dedc8aa74

In [5]:
pop.head()

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2020,2021,2022,2023,2024,2025,Unnamed: 70,source_name,load_timestamp,run_id
0,Aruba,ABW,"Population, total",SP.POP.TOTL,54922.0,55578.0,56320.0,57002.0,57619.0,58190.0,...,108587.0,107700.0,107310.0,107359.0,107995.0,NaN,NaN,pop.worldbank,2026-06-30 08:38:40,bf5bf24f-e937-427b-b79a-06c619e4f57a
1,Africa Eastern and Southern,AFE,"Population, total",SP.POP.TOTL,130075728.0,133534923.0,137171659.0,140945536.0,144904094.0,149033472.0,...,694446100.0,713090928.0,731821393.0,750491370.0,769280888.0,NaN,NaN,pop.worldbank,2026-06-30 08:38:40,bf5bf24f-e937-427b-b79a-06c619e4f57a
2,Afghanistan,AFG,"Population, total",SP.POP.TOTL,9035043.0,9214083.0,9404406.0,9604487.0,9814318.0,10036008.0,...,39068979.0,40000412.0,40578842.0,41454761.0,42647492.0,NaN,NaN,pop.worldbank,2026-06-30 08:38:40,bf5bf24f-e937-427b-b79a-06c619e4f57a
3,Africa Western and Central,AFW,"Population, total",SP.POP.TOTL,97630925.0,99706674.0,101854756.0,104089175.0,106388440.0,108772632.0,...,474569351.0,485920997.0,497387180.0,509398589.0,521764076.0,NaN,NaN,pop.worldbank,2026-06-30 08:38:40,bf5bf24f-e937-427b-b79a-06c619e4f57a
4,Angola,AGO,"Population, total",SP.POP.TOTL,5231654.0,5301583.0,5354310.0,5408320.0,5464187.0,5521981.0,...,33451132.0,34532429.0,35635029.0,36749906.0,37885849.0,NaN,NaN,pop.worldbank,2026-06-30 08:38:40,bf5bf24f-e937-427b-b79a-06c619e4f57a

In [6]:
matches.head()

,year,country,city,stage,home_team,away_team,home_score,away_score,outcome,win_conditions,winning_team,losing_team,date,month,dayofweek,source_name,load_timestamp,run_id
0,1930,Uruguay,Montevideo,Group 1,France,Mexico,4,1,H,NaN,France,Mexico,1930-07-13,Jul,Sunday,fifa_world_cup_archive,2026-06-29 17:08:30,46875d21-433c-4d67-be89-7b8b640985fe
1,1930,Uruguay,Montevideo,Group 4,Belgium,United States,0,3,A,NaN,United States,Belgium,1930-07-13,Jul,Sunday,fifa_world_cup_archive,2026-06-29 17:08:30,46875d21-433c-4d67-be89-7b8b640985fe
2,1930,Uruguay,Montevideo,Group 2,Brazil,Yugoslavia,1,2,A,NaN,Yugoslavia,Brazil,1930-07-14,Jul,Monday,fifa_world_cup_archive,2026-06-29 17:08:30,46875d21-433c-4d67-be89-7b8b640985fe
3,1930,Uruguay,Montevideo,Group 3,Peru,Romania,1,3,A,NaN,Romania,Peru,1930-07-14,Jul,Monday,fifa_world_cup_archive,2026-06-29 17:08:30,46875d21-433c-4d67-be89-7b8b640985fe
4,1930,Uruguay,Montevideo,Group 1,Argentina,France,1,0,H,NaN,Argentina,France,1930-07-15,Jul,Tuesday,fifa_world_cup_archive,2026-06-29 17:08:30,46875d21-433c-4d67-be89-7b8b640985fe

In [ ]:
tables = [pop, gdp, matches[matches['year']>=1998]]
table_names = ['pop', 'gdp', 'matches']
country_column = ['Country Name', 'Country Name', 'home_team']
country_tables = []

for i, name in enumerate(table_names) :
    print(name, 'table country number :', len(tables[i][country_column[i]].unique()))
    country_tables.append(tables[i][country_column[i]].unique())

pop table country number : 266
gdp table country number : 266
matches table country number : 62

14

['South Korea',
 'FR Yugoslavia',
 'England',
 'Scotland',
 'Republic of Ireland',
 'China PR',
 'Russia',
 'Turkey',
 'Czech Republic',
 'Iran',
 'Ivory Coast',
 'Slovakia',
 'North Korea',
 'Egypt']

### GDP - Population coutries comparision

In [25]:
[x for x in country_tables[0] if x not in country_tables[1]]

[]

In [26]:
[x for x in country_tables[1] if x not in country_tables[0]]

[]

### Matches Vs GDP-Population comparision

In [38]:
country_matches_not_found = [country for country in country_tables[-1] if country not in list(country_tables[0])+list(country_tables[1])]
print(len(country_matches_not_found), 'not found countries')
country_matches_not_found

14 not found countries

['South Korea',
 'FR Yugoslavia',
 'England',
 'Scotland',
 'Republic of Ireland',
 'China PR',
 'Russia',
 'Turkey',
 'Czech Republic',
 'Iran',
 'Ivory Coast',
 'Slovakia',
 'North Korea',
 'Egypt']

### Cration of mapping with valid values

In [35]:
country_matches_found = {
    country: country if country in list(country_tables[0]) + list(country_tables[1]) else "TO CHANGE"
    for country in country_tables[-1]
}
print(len(country_matches_found))
country_matches_found

62

{'Brazil': 'Brazil',
 'Morocco': 'Morocco',
 'Cameroon': 'Cameroon',
 'Italy': 'Italy',
 'France': 'France',
 'Paraguay': 'Paraguay',
 'Saudi Arabia': 'Saudi Arabia',
 'South Korea': 'TO CHANGE',
 'Netherlands': 'Netherlands',
 'Spain': 'Spain',
 'Argentina': 'Argentina',
 'Jamaica': 'Jamaica',
 'FR Yugoslavia': 'TO CHANGE',
 'England': 'TO CHANGE',
 'Germany': 'Germany',
 'Romania': 'Romania',
 'Scotland': 'TO CHANGE',
 'Chile': 'Chile',
 'South Africa': 'South Africa',
 'Nigeria': 'Nigeria',
 'Belgium': 'Belgium',
 'Japan': 'Japan',
 'United States': 'United States',
 'Colombia': 'Colombia',
 'Republic of Ireland': 'TO CHANGE',
 'Uruguay': 'Uruguay',
 'Croatia': 'Croatia',
 'China PR': 'TO CHANGE',
 'Russia': 'TO CHANGE',
 'Denmark': 'Denmark',
 'Sweden': 'Sweden',
 'Costa Rica': 'Costa Rica',
 'Mexico': 'Mexico',
 'Portugal': 'Portugal',
 'Tunisia': 'Tunisia',
 'Senegal': 'Senegal',
 'Slovenia': 'Slovenia',
 'Ecuador': 'Ecuador',
 'Turkey': 'TO CHANGE',
 'Poland': 'Poland',
 'Trinidad and Tobago': 'Trinidad and Tobago',
 'Angola': 'Angola',
 'Serbia': 'Serbia',
 'Australia': 'Australia',
 'Czech Republic': 'TO CHANGE',
 'Togo': 'Togo',
 'Iran': 'TO CHANGE',
 'Ivory Coast': 'TO CHANGE',
 'Ghana': 'Ghana',
 'Switzerland': 'Switzerland',
 'Ukraine': 'Ukraine',
 'Algeria': 'Algeria',
 'New Zealand': 'New Zealand',
 'Honduras': 'Honduras',
 'Greece': 'Greece',
 'Slovakia': 'TO CHANGE',
 'North Korea': 'TO CHANGE',
 'Bosnia and Herzegovina': 'Bosnia and Herzegovina',
 'Egypt': 'TO CHANGE',
 'Peru': 'Peru',
 'Iceland': 'Iceland',
 'Panama': 'Panama'}